import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { initializeApp } from 'firebase/app';
import { getAuth, GoogleAuthProvider, createUserWithEmailAndPassword, signInWithEmailAndPassword, signInWithPopup, signOut, onAuthStateChanged } from 'firebase/auth';
import { getFirestore, doc, setDoc, getDoc } from 'firebase/firestore';
import './styles.css';

const STORAGE_KEY = 'khusnul-trading-journal-data-v1';
const THEME_KEY = 'khusnul-trading-journal-theme-v1';
const TITLE_KEY = 'khusnul-trading-journal-title-v1';
const PIP_SIZE = 0.1;

const firebaseConfig = {
  apiKey: 'ISI_API_KEY_FIREBASE_KAMU',
  authDomain: 'ISI_AUTH_DOMAIN_FIREBASE_KAMU',
  projectId: 'ISI_PROJECT_ID_FIREBASE_KAMU',
  storageBucket: 'ISI_STORAGE_BUCKET_FIREBASE_KAMU',
  messagingSenderId: 'ISI_MESSAGING_SENDER_ID_FIREBASE_KAMU',
  appId: 'ISI_APP_ID_FIREBASE_KAMU',
};

const firebaseConfigured = !firebaseConfig.apiKey.includes('ISI_');
const firebaseApp = firebaseConfigured ? initializeApp(firebaseConfig) : null;
const auth = firebaseConfigured ? getAuth(firebaseApp) : null;
const db = firebaseConfigured ? getFirestore(firebaseApp) : null;

const themes = {
  ocean: { name: 'Ocean Blue', emoji: '🌊', bg: 'ocean', accent: '#0369a1' },
  pink: { name: 'Soft Pink', emoji: '🌸', bg: 'pink', accent: '#e11d48' },
  matcha: { name: 'Matcha Latte', emoji: '🌿', bg: 'matcha', accent: '#047857' },
  midnight: { name: 'Midnight Trader', emoji: '🌙', bg: 'midnight', accent: '#3b82f6' },
  cloud: { name: 'Cloud White', emoji: '☁️', bg: 'cloud', accent: '#0f172a' },
};

const initialForm = {
  date: new Date().toISOString().slice(0, 10), entryTime: new Date().toTimeString().slice(0, 5),
  pair: 'XAUUSD', direction: 'Buy', tradeStyle: 'Scalping', session: 'Asia', entry: '', currentPrice: '', takeProfit: '', stopLoss: '', lot: '', risk: '', status: 'Running', profitLoss: '', currency: 'IDR', setup: '', emotion: 'Tenang', maxFloatingPips: '', note: '', image: '',
};

function n(v){ const x = Number(v); return Number.isFinite(x) ? x : 0; }
function money(v,c){ return new Intl.NumberFormat(c === 'IDR' ? 'id-ID':'en-US',{style:'currency',currency:c,maximumFractionDigits:c==='IDR'?0:2}).format(n(v)); }
function pips(dir, entry, price){ if(!n(entry)||!n(price)) return 0; const raw = dir === 'Buy' ? n(price)-n(entry) : n(entry)-n(price); return Number((raw/PIP_SIZE).toFixed(1)); }
function riskPips(dir, entry, sl){ return Math.abs(pips(dir, entry, sl)); }
function tone(v){ return n(v)>0?'profit':n(v)<0?'loss':'neutral'; }
function monthKey(d){ return (d||'').slice(0,7); }
function monthLabel(k){ if(k==='all') return 'Semua Bulan'; const [y,m]=k.split('-'); return new Date(Number(y),Number(m)-1,1).toLocaleDateString('id-ID',{month:'long',year:'numeric'}); }
function entryQuality(v){ if(v===''||v==null) return 'Belum diisi. Isi floating maksimal supaya kualitas entry kebaca.'; const f=Math.abs(n(v)); if(f<=10) return 'Sniper entry — floating masih sangat kecil dan entry cukup presisi.'; if(f<=40) return 'Entry cukup rapi — masih dalam batas wajar, tapi timing bisa diasah lagi.'; if(f>70) return 'Floating jauh — cek session, timing, zona, dan konfirmasi entry.'; return 'Entry mulai kurang ideal — floating lumayan besar, perlu evaluasi timing.'; }
function groupBy(list, key){ return list.reduce((a,x)=>{ const k=x[key]||'Tidak diisi'; (a[k] ||= []).push(x); return a; },{}); }
function summary(list){ const total=list.length, wins=list.filter(t=>t.status==='Win').length, losses=list.filter(t=>t.status==='Loss').length; return { total, wins, losses, winRate: total?Math.round(wins/total*100):0, avgFloating: total?Number((list.reduce((s,t)=>s+Math.abs(n(t.maxFloatingPips)),0)/total).toFixed(1)):0, pnlIDR:list.filter(t=>t.currency==='IDR').reduce((s,t)=>s+n(t.profitLoss),0), pnlUSD:list.filter(t=>t.currency==='USD').reduce((s,t)=>s+n(t.profitLoss),0) }; }

function App(){
  const [trades,setTrades]=useState([]), [form,setForm]=useState(initialForm), [tab,setTab]=useState('dashboard'), [search,setSearch]=useState(''), [selectedMonth,setSelectedMonth]=useState('all');
  const [themeId,setThemeId]=useState('ocean'), [title,setTitle]=useState('Jurnal Trading'), [settings,setSettings]=useState(false);
  const [user,setUser]=useState(null), [loading,setLoading]=useState(firebaseConfigured), [email,setEmail]=useState(''), [password,setPassword]=useState(''), [authMode,setAuthMode]=useState('login'), [authError,setAuthError]=useState('');
  const theme=themes[themeId]||themes.ocean;

  useEffect(()=>{ try{ const saved=localStorage.getItem(STORAGE_KEY); if(saved) setTrades(JSON.parse(saved)); const th=localStorage.getItem(THEME_KEY); if(th&&themes[th]) setThemeId(th); const ti=localStorage.getItem(TITLE_KEY); if(ti) setTitle(ti); }catch{} },[]);
  useEffect(()=>{ if(!firebaseConfigured||!auth) return; return onAuthStateChanged(auth, async u=>{ setUser(u); setLoading(false); if(u&&db){ const snap=await getDoc(doc(db,'tradingJournals',u.uid)); if(snap.exists()){ const data=snap.data(); setTrades(data.trades||[]); setTitle(data.journalTitle||'Jurnal Trading'); if(themes[data.themeId]) setThemeId(data.themeId); } } }); },[]);
  useEffect(()=>{ localStorage.setItem(STORAGE_KEY,JSON.stringify(trades)); localStorage.setItem(THEME_KEY,themeId); localStorage.setItem(TITLE_KEY,title); if(firebaseConfigured&&db&&user){ setDoc(doc(db,'tradingJournals',user.uid),{trades,journalTitle:title,themeId,updatedAt:new Date().toISOString()},{merge:true}); } },[trades,themeId,title,user]);

  const monthOptions=useMemo(()=>Array.from(new Set([new Date().toISOString().slice(0,7),...trades.map(t=>monthKey(t.date)).filter(Boolean)])).sort().reverse(),[trades]);
  const monthTrades=useMemo(()=>selectedMonth==='all'?trades:trades.filter(t=>monthKey(t.date)===selectedMonth),[trades,selectedMonth]);
  const filtered=useMemo(()=>{ const q=search.toLowerCase(); return monthTrades.filter(t=>!q||[t.pair,t.direction,t.tradeStyle,t.session,t.status,t.setup,t.emotion,t.note].join(' ').toLowerCase().includes(q)); },[monthTrades,search]);
  const stats=useMemo(()=>({ total:trades.length, win:trades.filter(t=>t.status==='Win').length, loss:trades.filter(t=>t.status==='Loss').length, running:trades.filter(t=>t.status==='Running').length, winRate:trades.length?Math.round(trades.filter(t=>t.status==='Win').length/trades.length*100):0, pnlIDR:trades.filter(t=>t.currency==='IDR').reduce((s,t)=>s+n(t.profitLoss),0), pnlUSD:trades.filter(t=>t.currency==='USD').reduce((s,t)=>s+n(t.profitLoss),0), floating:Number(trades.filter(t=>t.status==='Running').reduce((s,t)=>s+pips(t.direction,t.entry,t.currentPrice),0).toFixed(1)) }),[trades]);
  const report=useMemo(()=>{ const total=monthTrades.length, wins=monthTrades.filter(t=>t.status==='Win').length, losses=monthTrades.filter(t=>t.status==='Loss').length, be=monthTrades.filter(t=>t.status==='BE').length; const closed=monthTrades.filter(t=>t.profitLoss!==''); const styleGroups=Object.entries(groupBy(monthTrades,'tradeStyle')).map(([name,items])=>({name,...summary(items)})); const emotionGroups=Object.entries(groupBy(monthTrades,'emotion')).map(([name,items])=>({name,...summary(items)})); const sessionGroups=Object.entries(groupBy(monthTrades,'session')).map(([name,items])=>({name,...summary(items)})); return { total,wins,losses,be,winRate:total?Math.round(wins/total*100):0,pnlIDR:summary(monthTrades).pnlIDR,pnlUSD:summary(monthTrades).pnlUSD,avgFloating:summary(monthTrades).avgFloating,slAvg:total?Number((monthTrades.reduce((s,t)=>s+riskPips(t.direction,t.entry,t.stopLoss),0)/total).toFixed(1)):0,sniper:monthTrades.filter(t=>t.maxFloatingPips!==''&&Math.abs(n(t.maxFloatingPips))<=10).length, clean:monthTrades.filter(t=>Math.abs(n(t.maxFloatingPips))>10&&Math.abs(n(t.maxFloatingPips))<=40).length, heavy:monthTrades.filter(t=>Math.abs(n(t.maxFloatingPips))>70).length,best:[...closed].sort((a,b)=>n(b.profitLoss)-n(a.profitLoss))[0],worst:[...closed].sort((a,b)=>n(a.profitLoss)-n(b.profitLoss))[0],styleGroups,emotionGroups,sessionGroups,bestSession:[...sessionGroups].sort((a,b)=>b.winRate-a.winRate||a.avgFloating-b.avgFloating)[0]}; },[monthTrades]);

  const live=pips(form.direction,form.entry,form.currentPrice), tp=pips(form.direction,form.entry,form.takeProfit), sl=riskPips(form.direction,form.entry,form.stopLoss);
  function change(e){ const {name,value}=e.target; setForm(f=>({...f,[name]:value})); }
  function image(e){ const file=e.target.files?.[0]; if(!file) return; const r=new FileReader(); r.onload=()=>setForm(f=>({...f,image:String(r.result||'')})); r.readAsDataURL(file); }
  function add(e){ e.preventDefault(); if(!form.entry) return; setTrades(t=>[{...form,id:crypto.randomUUID(),createdAt:new Date().toISOString()},...t]); setForm({...initialForm,date:new Date().toISOString().slice(0,10),entryTime:new Date().toTimeString().slice(0,5)}); setTab('history'); }
  async function emailAuth(e){ e.preventDefault(); setAuthError(''); try{ if(!auth) throw new Error('Firebase belum dikonfigurasi.'); authMode==='register'?await createUserWithEmailAndPassword(auth,email,password):await signInWithEmailAndPassword(auth,email,password); }catch(err){ setAuthError(err.message); } }
  async function googleLogin(){ try{ if(!auth) throw new Error('Firebase belum dikonfigurasi.'); await signInWithPopup(auth,new GoogleAuthProvider()); }catch(err){ setAuthError(err.message); } }

  if(loading) return <main className={`app ${theme.bg}`}><div className="card center"><h2>Membuka jurnal...</h2></div></main>;
  if(firebaseConfigured&&!user) return <Auth theme={theme} email={email} setEmail={setEmail} password={password} setPassword={setPassword} authMode={authMode} setAuthMode={setAuthMode} authError={authError} emailAuth={emailAuth} googleLogin={googleLogin}/>;

  return <main className={`app ${theme.bg}`} style={{'--accent':theme.accent}}>
    <div className="wrap">
      <section className="hero card">
        <div><p className="eyebrow">Trading Journal</p><div className="title-row"><h1>{title}</h1><button className="ghost" onClick={()=>{const x=prompt('Ubah nama jurnal trading:',title); if(x?.trim()) setTitle(x.trim());}}>Edit Nama</button></div><p className="muted">Catat entry, session, gaya trade, floating, TP, SL, screenshot chart, emosi, dan evaluasi trade.</p>{!firebaseConfigured&&<p className="notice">Mode local/offline. Isi firebaseConfig untuk mengaktifkan login online.</p>}</div>
        <div className="profit-grid">{user&&<div className="mini-card span2"><small>Login sebagai</small><b>{user.email||user.displayName}</b><button className="ghost small" onClick={()=>signOut(auth)}>Logout</button></div>}<ProfitCard label="Total P/L IDR" value={stats.pnlIDR} currency="IDR"/><ProfitCard label="Total P/L USD" value={stats.pnlUSD} currency="USD"/></div>
      </section>
      <nav className="tabs card"><button className={tab==='dashboard'?'active':''} onClick={()=>setTab('dashboard')}>Dashboard</button><button className={tab==='add'?'active':''} onClick={()=>setTab('add')}>Tambah</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>Riwayat</button><button className={tab==='report'?'active':''} onClick={()=>setTab('report')}>Laporan</button><button onClick={()=>setSettings(true)}>⚙️</button></nav>
      {tab==='dashboard'&&<Dashboard stats={stats} report={report} setTab={setTab}/>} 
      {tab==='add'&&<TradeForm form={form} change={change} image={image} add={add} live={live} tp={tp} sl={sl}/>} 
      {tab==='history'&&<History trades={filtered} search={search} setSearch={setSearch} del={id=>setTrades(t=>t.filter(x=>x.id!==id))}/>} 
      {tab==='report'&&<Report selectedMonth={selectedMonth} setSelectedMonth={setSelectedMonth} monthOptions={monthOptions} report={report}/>} 
    </div>
    {settings&&<SettingsPanel themeId={themeId} setThemeId={setThemeId} close={()=>setSettings(false)}/>} 
  </main>;
}

function Auth(p){return <main className={`app ${p.theme.bg}`}><form className="auth card" onSubmit={p.emailAuth}><p className="eyebrow">Trading Journal</p><h1>Masuk ke Jurnal</h1><p className="muted">Login supaya data tersimpan online dan bisa dibuka dari device lain.</p><button type="button" className="full ghost" onClick={p.googleLogin}>Login dengan Google</button><div className="sep">atau email</div><Input label="Email" type="email" value={p.email} onChange={e=>p.setEmail(e.target.value)}/><Input label="Password" type="password" value={p.password} onChange={e=>p.setPassword(e.target.value)}/>{p.authError&&<p className="error">{p.authError}</p>}<button className="full primary">{p.authMode==='register'?'Daftar':'Login'}</button><button type="button" className="link" onClick={()=>p.setAuthMode(p.authMode==='register'?'login':'register')}>{p.authMode==='register'?'Sudah punya akun? Login':'Belum punya akun? Daftar'}</button></form></main>}
function Dashboard({stats,report,setTab}){return <section className="space"><div className="stat-grid"><Stat label="Total" value={stats.total}/><Stat label="Win" value={stats.win}/><Stat label="Loss" value={stats.loss}/><Stat label="Running" value={stats.running}/><Stat label="Win Rate" value={stats.winRate+'%'}/><Stat label="Floating" value={stats.floating+' pips'}/></div><div className="dash-grid"><div className="card"><h2>Aksi Cepat</h2><p className="muted">Mulai catat trade baru atau cek laporan performa bulananmu.</p><button className="primary full" onClick={()=>setTab('add')}>Tambah Trade</button><button className="ghost full" onClick={()=>setTab('report')}>Lihat Laporan</button></div><div className="card wide"><h2>Ringkasan Bulan Ini</h2><div className="stat-grid compact"><Stat label="Trade" value={report.total}/><Stat label="Win Rate" value={report.winRate+'%'}/><Stat label="Avg Floating" value={report.avgFloating+' pips'}/><Stat label="Sniper" value={report.sniper+' trade'}/></div></div></div></section>}
function TradeForm({form,change,image,add,live,tp,sl}){return <form className="card form" onSubmit={add}><h2>Tambah Trade</h2><div className="grid3"><Input label="Tanggal" name="date" type="date" value={form.date} onChange={change}/><Input label="Jam Entry" name="entryTime" type="time" value={form.entryTime} onChange={change}/><Input label="Pair" name="pair" value={form.pair} onChange={change}/></div><div className="grid3"><Select label="Posisi" name="direction" value={form.direction} onChange={change} options={['Buy','Sell']}/><Select label="Gaya Trade" name="tradeStyle" value={form.tradeStyle} onChange={change} options={['Scalping','Intraday','Swing']}/><Select label="Session" name="session" value={form.session} onChange={change} options={['Asia','London','Eropa','New York']}/></div><Select label="Status" name="status" value={form.status} onChange={change} options={['Running','Win','Loss','BE']}/><Input label="Setup / Alasan Entry" name="setup" value={form.setup} onChange={change}/><div className="grid2"><Input label="Zona Entry" name="entry" type="number" step="any" value={form.entry} onChange={change}/><Input label="Harga Sekarang" name="currentPrice" type="number" step="any" value={form.currentPrice} onChange={change}/></div><div className="grid2"><Input label="TP / Exit Price" name="takeProfit" type="number" step="any" value={form.takeProfit} onChange={change}/><Input label="Stop Loss" name="stopLoss" type="number" step="any" value={form.stopLoss} onChange={change}/></div><div className="grid3"><Box label="Running" value={(live>0?'+':'')+live+' pips'} tone={live<0?'loss':'profit'}/><Box label="TP" value={(tp>0?'+':'')+tp+' pips'} tone="info"/><Box label="SL" value={sl+' pips'} tone="warn"/></div><div className="grid3"><Input label="Lot" name="lot" type="number" value={form.lot} onChange={change}/><Input label="Risk %" name="risk" type="number" value={form.risk} onChange={change}/><Select label="P/L" name="currency" value={form.currency} onChange={change} options={['IDR','USD']}/></div><Input label={`Nominal P/L ${form.currency}`} name="profitLoss" type="number" value={form.profitLoss} onChange={change}/><Select label="Emosi Saat Entry" name="emotion" value={form.emotion} onChange={change} options={['Tenang','Disiplin','Ragu','Takut','FOMO','Greedy']}/><Input label="Floating Maksimal Sebelum Profit / Close (pips)" name="maxFloatingPips" type="number" value={form.maxFloatingPips} onChange={change}/><label className="field"><span>Upload Gambar Chart</span><input type="file" accept="image/*" onChange={image}/>{form.image&&<img className="preview" src={form.image}/>}</label><label className="field"><span>Catatan Evaluasi</span><textarea name="note" value={form.note} onChange={change} rows="4"/></label><button className="primary full">Simpan Trade</button></form>}
function History({trades,search,setSearch,del}){return <section className="card"><div className="head"><h2>Riwayat Trade</h2><Input placeholder="Cari pair, setup, emosi..." value={search} onChange={e=>setSearch(e.target.value)}/></div>{trades.length===0?<p className="empty">Belum ada trade.</p>:trades.map(t=><Trade key={t.id} trade={t} del={del}/>)}</section>}
function Trade({trade,del}){const run=pips(trade.direction,trade.entry,trade.currentPrice), tp=pips(trade.direction,trade.entry,trade.takeProfit), sl=riskPips(trade.direction,trade.entry,trade.stopLoss), mf=trade.maxFloatingPips?Math.abs(n(trade.maxFloatingPips)):0;return <article className={`trade ${tone(trade.profitLoss)}`}><div className="trade-top"><div><b>{trade.pair}</b> <Badge>{trade.direction}</Badge><Badge>{trade.tradeStyle}</Badge><Badge>{trade.session}</Badge><Badge>{trade.status}</Badge><p>{trade.date} • {trade.entryTime||'--:--'} • Emosi: {trade.emotion}</p></div><button className="icon" onClick={()=>del(trade.id)}>🗑</button></div>{trade.image&&<img className="chart" src={trade.image}/>}<div className="stat-grid compact"><Stat label="Entry" value={trade.entry||'-'}/><Stat label="Now" value={trade.currentPrice||'-'}/><Stat label="TP" value={trade.takeProfit||'-'}/><Stat label="SL" value={trade.stopLoss||'-'}/><Stat label="Lot" value={trade.lot||'-'}/><Stat label="P/L" value={money(trade.profitLoss,trade.currency)} /></div><div className="grid4"><Box label="Running" value={(run>0?'+':'')+run+' pips'} tone={run<0?'loss':'profit'}/><Box label="TP" value={(tp>0?'+':'')+tp+' pips'} tone="info"/><Box label="SL" value={sl+' pips'} tone="warn"/><Box label="Floating Dulu" value={trade.maxFloatingPips?'-'+mf+' pips':'0 pips'} tone={mf>40?'loss':mf>10?'warn':'profit'}/></div>{trade.setup&&<p><b>Setup:</b> {trade.setup}</p>}{trade.note&&<p><b>Evaluasi:</b> {trade.note}</p>}<p className="quality"><b>Cek kualitas entry:</b> {entryQuality(trade.maxFloatingPips)}</p></article>}
function Report({selectedMonth,setSelectedMonth,monthOptions,report}){return <section className="card"><div className="head"><div><p className="eyebrow">Monthly Report</p><h2>Laporan Bulanan Trading</h2><p className="muted">Ringkasan: {monthLabel(selectedMonth)}</p></div><Select label="Pilih Bulan" value={selectedMonth} onChange={e=>setSelectedMonth(e.target.value)} options={['all',...monthOptions]} labels={{all:'Semua Bulan'}}/></div><div className="stat-grid"><Stat label="Total Trade" value={report.total}/><Stat label="Win Rate" value={report.winRate+'%'}/><Stat label="Win/Loss/BE" value={`${report.wins}/${report.losses}/${report.be}`}/><Stat label="P/L IDR" value={money(report.pnlIDR,'IDR')}/><Stat label="P/L USD" value={money(report.pnlUSD,'USD')}/><Stat label="Avg Floating" value={report.avgFloating+' pips'}/></div><div className="grid4"><Box label="Sniper ≤10" value={report.sniper+' trade'} tone="profit"/><Box label="Rapi 10–40" value={report.clean+' trade'} tone="info"/><Box label="Floating >70" value={report.heavy+' trade'} tone="loss"/><Box label="Avg SL" value={report.slAvg+' pips'} tone="warn"/></div><div className="dash-grid three"><Group title="Gaya Trade" data={report.styleGroups}/><Group title="Emosi" data={report.emotionGroups}/><Group title="Session" data={report.sessionGroups}/></div><div className="dash-grid three"><Highlight title="Best Trade" trade={report.best}/><Highlight title="Worst Trade" trade={report.worst}/><div className="mini-card"><h3>Insight Otomatis</h3><p>{report.total?`Entry ${report.sniper>=report.heavy?'cukup presisi':'perlu evaluasi timing/session'}. Session terbaik: ${report.bestSession?.name||'-'}.`:'Belum ada data untuk bulan ini.'}</p></div></div></section>}
function SettingsPanel({themeId,setThemeId,close}){return <div className="modal"><section className="card settings"><div className="head"><h2>Settings Warna</h2><button onClick={close}>✕</button></div><div className="theme-grid">{Object.entries(themes).map(([id,t])=><button key={id} onClick={()=>setThemeId(id)} className={`theme ${t.bg} ${themeId===id?'chosen':''}`}><span>{t.emoji}</span><b>{t.name}</b><small>Background, card, tab, tombol berubah.</small></button>)}</div><button className="ghost full" onClick={()=>setThemeId('ocean')}>Reset ke Ocean Blue</button></section></div>}
function Input({label,...props}){return <label className="field">{label&&<span>{label}</span>}<input {...props}/></label>}
function Select({label,options,labels={},...props}){return <label className="field">{label&&<span>{label}</span>}<select {...props}>{options.map(o=><option key={o} value={o}>{labels[o]|| (o.includes('-')?monthLabel(o):o)}</option>)}</select></label>}
function Stat({label,value}){return <div className="mini-card"><small>{label}</small><b>{value}</b></div>}
function ProfitCard({label,value,currency}){return <div className={`mini-card ${tone(value)}`}><small>{label}</small><b>{money(value,currency)}</b></div>}
function Box({label,value,tone}){return <div className={`box ${tone}`}><small>{label}</small><b>{value}</b></div>}
function Badge({children}){return <span className="badge">{children}</span>}
function Group({title,data}){return <div className="mini-card"><h3>{title}</h3>{data.length?data.map(g=><p key={g.name}><b>{g.name}</b> — {g.winRate}% WR, {g.total} trade, avg floating {g.avgFloating} pips</p>):<p>Belum ada data.</p>}</div>}
function Highlight({title,trade}){return <div className="mini-card"><h3>{title}</h3>{trade?<><b>{trade.pair} • {trade.direction}</b><p>{trade.date} • {trade.tradeStyle}</p><h2>{money(trade.profitLoss,trade.currency)}</h2><p>{trade.setup||'Setup belum diisi.'}</p></>:<p>Belum ada data P/L.</p>}</div>}

createRoot(document.getElementById('root')).render(<App />);
